#ifndef RG_STATICCODE_PLUGIN_GLOBAL_H
#define RG_STATICCODE_PLUGIN_GLOBAL_H

#include <QtGlobal>

#if defined(RG_STATICCODE_PLUGIN_LIBRARY)
#  define RG_STATICCODE_PLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RG_STATICCODE_PLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RG_STATICCODE_PLUGIN_GLOBAL_H

